import { CompiledContract } from "@midnight-ntwrk/midnight-js-protocol/compact-js";
import { invoiceWitnesses } from "./private-state";

export type InvoiceLedgerEntry = { commitment: Uint8Array; tokenColor: Uint8Array; status: number; acceptanceNullifier: Uint8Array; paymentNullifier: Uint8Array };
export type InvoiceLedgerView = { protocolVersion: bigint; invoices: { member(key: Uint8Array): boolean; lookup(key: Uint8Array): InvoiceLedgerEntry }; usedNullifiers: { member(key: Uint8Array): boolean } };
export type GeneratedInvoiceModule = {
  Contract: new (...args: unknown[]) => unknown;
  ledger(state: unknown): InvoiceLedgerView;
  pureCircuits: {
    deriveAuthorityPublicKey(secret: Uint8Array): Uint8Array;
    invoiceCommitment(invoiceId: Uint8Array, amountMinor: bigint, taxMinor: bigint, payerPublicKey: Uint8Array, supplierPublicKey: Uint8Array, supplierCoinPublicKey: Uint8Array, dueAt: bigint, salt: Uint8Array): Uint8Array;
  };
  InvoiceStatus: { Created: number; Accepted: number; Funded: number; Paid: number };
};

function validate(value: unknown): GeneratedInvoiceModule {
  if (!value || typeof value !== "object") throw new Error("Generated Blackout Invoice module did not load");
  const module = value as Partial<GeneratedInvoiceModule>;
  if (typeof module.Contract !== "function" || typeof module.ledger !== "function") throw new Error("Generated contract exports are missing");
  if (!module.pureCircuits || typeof module.pureCircuits.deriveAuthorityPublicKey !== "function" || typeof module.pureCircuits.invoiceCommitment !== "function") throw new Error("Generated invoice pure circuits are missing");
  if (!module.InvoiceStatus) throw new Error("Generated InvoiceStatus enum is missing");
  return module as GeneratedInvoiceModule;
}

export async function createCompiledInvoiceContract() {
  if (typeof window === "undefined") throw new Error("Compact bindings require a browser");
  // @ts-ignore generated by Compact immediately before Next build
  const loaded = await import("../../generated/invoice/index.js");
  const generated = validate(loaded);
  const compiledContract = CompiledContract.make<any>("BlackoutInvoice", generated.Contract as any).pipe(
    CompiledContract.withWitnesses(invoiceWitnesses() as any),
    CompiledContract.withCompiledFileAssets(`${window.location.origin}/invoice`),
  );
  return { generated, compiledContract };
}
