"use client";
import { useMemo, useState } from "react";
import { bytesToHex, randomBytes32 } from "@/lib/midnight/bytes";
import { connectMidnightWallet, type ConnectedWallet } from "@/lib/midnight/wallet";
import { acceptInvoiceOnChain, createAuthority, createInvoiceOnChain, fundInvoiceOnChain, getInvoiceStatus, initializeInvoiceRuntime, payInvoiceOnChain } from "@/lib/midnight/runtime";

type Log={at:string;message:string}; const now=()=>new Date().toLocaleTimeString();
export default function InvoiceWorkbench(){
  const [wallet,setWallet]=useState<ConnectedWallet|null>(null), [ready,setReady]=useState(false), [busy,setBusy]=useState(false), [logs,setLogs]=useState<Log[]>([]);
  const [contract,setContract]=useState(""), [password,setPassword]=useState(""), [invoiceId,setInvoiceId]=useState(""), [token,setToken]=useState("");
  const [amount,setAmount]=useState("100000"), [tax,setTax]=useState("0"), [dueAt,setDueAt]=useState(String(Math.floor(Date.now()/1000)+2592000));
  const [payerSecret,setPayerSecret]=useState(""), [payerPublic,setPayerPublic]=useState(""), [supplierSecret,setSupplierSecret]=useState(""), [supplierPublic,setSupplierPublic]=useState(""), [supplierCoin,setSupplierCoin]=useState(""), [salt,setSalt]=useState(""), [status,setStatus]=useState("NOT CREATED");
  const draft=useMemo(()=>({invoiceIdHex:invoiceId,tokenColorHex:token,witness:{amountMinor:BigInt(amount||"0"),taxMinor:BigInt(tax||"0"),payerPublicKeyHex:payerPublic,supplierPublicKeyHex:supplierPublic,supplierCoinPublicKeyHex:supplierCoin,dueAt:BigInt(dueAt||"0"),saltHex:salt}}),[invoiceId,token,amount,tax,payerPublic,supplierPublic,supplierCoin,dueAt,salt]);
  const log=(message:string)=>setLogs(v=>[{at:now(),message},...v].slice(0,20));
  const act=async(fn:()=>Promise<void>)=>{setBusy(true);try{await fn()}catch(e){log(`FAIL CLOSED — ${e instanceof Error?e.message:String(e)}`)}finally{setBusy(false)}};
  return <main className="shell">
    <header><div><small>BLACKOUT / MIDNIGHT</small><h1>INVOICE</h1></div><code>PROVE COMMERCE. REVEAL NOTHING ELSE.</code></header>
    <section className="hero"><p>MILESTONES 1–5 / LIVE WORKBENCH</p><h2>CONFIDENTIAL<br/>COMMERCIAL<br/>SETTLEMENT.</h2><span>No fake transaction state. PAID appears only after Midnight ledger confirmation.</span></section>
    <div className="grid">
      <section className="panel"><h3>01 / NETWORK</h3><button disabled={busy} onClick={()=>act(async()=>{const w=await connectMidnightWallet();setWallet(w);setSupplierCoin(w.addresses.shieldedCoinPublicKey.replace(/^0x/i,""));log(`Lace connected / ${w.networkId}`)})}>{wallet?`CONNECTED / ${wallet.name}`:"CONNECT LACE"}</button><input type="password" placeholder="Private-state password (16+ chars)" value={password} onChange={e=>setPassword(e.target.value)}/><input placeholder="Existing contract address" value={contract} onChange={e=>setContract(e.target.value)}/><div className="row"><button disabled={!wallet||busy} onClick={()=>act(async()=>{if(!wallet)throw new Error("Connect Lace first");const x=await initializeInvoiceRuntime({wallet,privateStatePassword:password,mode:"deploy"});setContract(x.contractAddress);setReady(true);log(`REAL contract deployed / ${x.deploymentTransactionId??"tx unavailable"}`)})}>DEPLOY</button><button disabled={!wallet||busy} onClick={()=>act(async()=>{if(!wallet)throw new Error("Connect Lace first");await initializeInvoiceRuntime({wallet,privateStatePassword:password,mode:"join",contractAddress:contract});setReady(true);log("Joined verified contract")})}>JOIN</button></div></section>
      <section className="panel"><h3>02 / AUTHORITIES</h3><div className="row"><button disabled={!ready||busy} onClick={()=>act(async()=>{const a=await createAuthority();setSupplierSecret(a.secretHex);setSupplierPublic(a.publicKeyHex);log("Supplier authority generated locally")})}>NEW SUPPLIER KEY</button><button disabled={!ready||busy} onClick={()=>act(async()=>{const a=await createAuthority();setPayerSecret(a.secretHex);setPayerPublic(a.publicKeyHex);log("Payer authority generated locally")})}>NEW PAYER KEY</button></div><label>Supplier public key<input value={supplierPublic} onChange={e=>setSupplierPublic(e.target.value)}/></label><label>Payer public key<input value={payerPublic} onChange={e=>setPayerPublic(e.target.value)}/></label></section>
      <section className="panel wide"><h3>03 / PRIVATE INVOICE</h3><div className="fields"><label>Invoice ID<input value={invoiceId} onChange={e=>setInvoiceId(e.target.value)}/></label><button onClick={()=>setInvoiceId(bytesToHex(randomBytes32()))}>RANDOM ID</button><label>Token colour<input value={token} onChange={e=>setToken(e.target.value)}/></label><label>Amount minor<input value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Tax minor<input value={tax} onChange={e=>setTax(e.target.value)}/></label><label>Due unix<input value={dueAt} onChange={e=>setDueAt(e.target.value)}/></label><label>Supplier shielded coin key<input value={supplierCoin} onChange={e=>setSupplierCoin(e.target.value.replace(/^0x/i,""))}/></label><label>Salt<input value={salt} onChange={e=>setSalt(e.target.value)}/></label><button onClick={()=>setSalt(bytesToHex(randomBytes32()))}>RANDOM SALT</button></div><p className="privacy">PUBLIC → commitment / token / status / nullifiers &nbsp;&nbsp; PRIVATE → amount / tax / parties / payout key / due date / salt</p></section>
      <section className="panel wide"><h3>04 / SETTLEMENT <b>{status}</b></h3><div className="flow"><button disabled={!ready||busy} onClick={()=>act(async()=>{const x=await createInvoiceOnChain({...draft,supplierSecretHex:supplierSecret});setStatus("CREATED");log(`Invoice registered / ${x.transactionId}`)})}>CREATE</button><i>→</i><button disabled={!ready||busy} onClick={()=>act(async()=>{const x=await acceptInvoiceOnChain({...draft,payerSecretHex:payerSecret});setStatus("ACCEPTED");log(`Accepted / ${x.transactionId}`)})}>ACCEPT</button><i>→</i><button disabled={!ready||busy} onClick={()=>act(async()=>{const x=await fundInvoiceOnChain({invoiceIdHex:invoiceId,payerSecretHex:payerSecret});setStatus("FUNDED");log(`Shielded funds committed / ${x.transactionId}`)})}>FUND</button><i>→</i><button disabled={!ready||busy} onClick={()=>act(async()=>{const x=await payInvoiceOnChain({invoiceIdHex:invoiceId,payerSecretHex:payerSecret});setStatus("PAID");log(`REAL settlement confirmed / ${x.transactionId}`)})}>PAY</button><button disabled={!ready||busy||!invoiceId} onClick={()=>act(async()=>{const s=await getInvoiceStatus(invoiceId);setStatus(s);log(`Indexer state / ${s}`)})}>REFRESH LEDGER</button></div></section>
      <section className="panel wide terminal"><h3>05 / PROTOCOL LOG</h3>{logs.length?logs.map((l,i)=><div className="log" key={i}><time>{l.at}</time><span>{l.message}</span></div>):<p>No actions yet.</p>}</section>
    </div>
  </main>
}
